---
- name: Mirror Images
  hosts: provisioner
  # become: true
  vars:
    # Define your variables for the mirror registry
    quay_target_hostname: "{{ ansible_fqdn }}"
    quay_target_port: 8443
    quay_user: quayadmin
    quay_password: "password"
    oc_install_dir: "/usr/local/bin"

  tasks:

    - name: Check if oc binary is already installed
      ansible.builtin.command: "{{ oc_install_dir }}/oc version --client"
      register: oc_installed
      ignore_errors: true

    - name: Download OpenShift client (oc) binary if not already installed
      ansible.builtin.get_url:
        url: "{{ source_urls['client'] }}"
        dest: "/tmp/openshift-client-linux.tar.gz"
      when: oc_installed.failed

    - name: Extract OpenShift client (oc) binary if not already installed
      become: true
      ansible.builtin.unarchive:
        src: "/tmp/openshift-client-linux.tar.gz"
        dest: "{{ oc_install_dir }}"
        remote_src: false
        creates: "{{ oc_install_dir }}/oc"
      when: oc_installed.failed

    - name: Set executable permission for oc binary
      become: true
      ansible.builtin.file:
        path: "{{ oc_install_dir }}/oc"
        mode: '0755'
      when: oc_installed.failed

    - name: Verify oc installation
      ansible.builtin.command: "{{ oc_install_dir }}/oc version --client"
      register: oc_installed_version
      changed_when: false

    - name: Display oc version
      ansible.builtin.debug:
        msg: "The installed OpenShift client (oc) version is: {{ oc_installed_version.stdout }}"
