---
- name: Install Mirror Registry for Red Hat OpenShift
  hosts: provisioner
  # become: true
  vars:
    # Define your variables for the mirror registry
    mirror_registry_bin_dir: "/tmp/mirror-registry/"
    mirror_registry_tar: "{{ mirror_registry_bin_dir }}/mirror-registry.tar.gz"
    quay_hostname: "registry.example.com"
    quay_root: "/opt/mirror-registry"

  tasks:
    - name: Create directory {{ quay_root }}
      become: true
      ansible.builtin.file:
        dest: "{{ quay_root }}"
        state: directory
        mode: "0755"
        owner: lab-user
        group: users

    - name: Create directory {{ mirror_registry_bin_dir }}
      become: true
      ansible.builtin.file:
        dest: "{{ mirror_registry_bin_dir }}"
        state: directory
        mode: "0755"
        owner: lab-user
        group: users

    - name: Download the mirror registry package
      ansible.builtin.get_url:
        url: "{{ source_urls['mirror_registry'] }}"
        dest: "{{ mirror_registry_tar }}"
        mode: '0644'

    - name: Extract the mirror registry package
      ansible.builtin.unarchive:
        src: "{{ mirror_registry_tar }}"
        dest: "{{ mirror_registry_bin_dir }}"
        remote_src: no
        creates: "{{ mirror_registry_bin_dir }}/mirror-registry"
        mode: '0755'

    - name: Run the mirror-registry install command
      ansible.builtin.command:
        cmd: >
          ./mirror-registry install
          --quayHostname {{ quay_hostname }}
          --quayRoot {{ quay_root | default('/opt/mirror-registry')}}
          --initUser "{{ quay_user | default('init') }}"
          --initPassword "{{ quay_password | default('password')}}"
          --additionalArgs "-v"
          -v
        chdir: "{{ mirror_registry_bin_dir }}"

    - name: Log in to the mirror registry using Podman
      containers.podman.podman_login:
        username: "{{ quay_user | default('init') }}"
        password: "{{ quay_password | default('password')}}"
        registry: "{{ quay_hostname }}:{{ quay_port }}"
        tlsverify: false
      when: quay_hostname is defined

    - name: Debug - Quay hostname and login info
      ansible.builtin.debug:
        msg: "Login to the registry at https://{{ quay_hostname }}:{{ port }} with the username 'init' and the provided password."

    - name: Provide next steps for the user
      ansible.builtin.debug:
        msg: |
          To continue, you can now mirror OpenShift Container Platform images.
          Use 'podman login' to log in to the registry if needed.
          More info: See the 'Mirroring OpenShift Container Platform images' or 'Mirroring Operator catalogs' documentation.
