---
- name: Cluster upgrade preflight
  hosts: provisioner
  gather_facts: true
  any_errors_fatal: true
  vars:
    target_node_groups: []
  tasks:
    - name: Include cluster preflight tasks
      ansible.builtin.include_tasks: "include/upgrade/cluster_preflight.yaml"
      when: fw_upgrade_only != true

- name: Node upgrade preflight
  hosts: openshift_nodes
  gather_facts: false
  any_errors_fatal: true
  vars:
    target_node_groups: []
  tasks:
    - name: Gather node information
      ansible.builtin.include_tasks: "include/gather_{{ pm_type }}_facts.yaml"
      when: node_group is defined and node_group in target_node_groups

    - name: Include node preflight tasks
      ansible.builtin.include_tasks: "include/upgrade/node_preflight.yaml"
      when: node_group is defined and node_group in target_node_groups

- name: Control plane upgrade
  hosts: provisioner
  gather_facts: false
  vars:
    target_node_groups: []
  tasks:
    - name: Include control plane upgrade tasks
      ansible.builtin.include_tasks: "include/upgrade/control_plane.yaml"
      when: fw_upgrade_only != true and control_plane_upgrade_required

- name: Loop over node groups
  hosts: openshift_nodes
  gather_facts: false
  serial: "{{ node_update_serial | default(32) }}"
  vars:
    target_node_groups: []
  tasks:
    - name: Include node group update tasks
      ansible.builtin.include_tasks: "include/upgrade/_node_upgrade_loop.yaml"
      loop_control:
        loop_var: active_node_group
      loop: "{{ target_node_groups }}"

- name: Cluster upgrade cleanup
  hosts: provisioner
  gather_facts: false
  vars:
    target_node_groups: []
  tasks:
    - name: Include cluster cleanup tasks
      ansible.builtin.include_tasks: "include/upgrade/cluster_cleanup.yaml"
