- name: Include node upgrade tasks for node group
  ansible.builtin.include_tasks: "include/upgrade/upgrade_worker_node.yaml"
  when: node_group is defined and node_group in target_node_groups and node_group == active_node_group and firmware_update_required

- name: Include machine pool upgrade tasks
  ansible.builtin.include_tasks: "include/upgrade/upgrade_worker_group.yaml"
  when: fw_upgrade_only != true and active_node_group in target_node_groups and control_plane_upgrade_required

- name: Include node cleanup tasks for node group
  ansible.builtin.include_tasks: "include/upgrade/node_cleanup.yaml"
  when: node_group is defined and node_group in target_node_groups and node_group == active_node_group
