- name: Power off server
  community.general.hpilo_boot:
    host: "{{ bmc_ip_addr }}"
    login: "{{ secret_bmc_username }}"
    password: "{{ secret_bmc_password }}"
    state: poweroff
  delegate_to: localhost

- name: Wait 20 seconds for server to power off
  ansible.builtin.pause:
    seconds: 20

- name: Boot server from ISO
  community.general.hpilo_boot:
    host: "{{ bmc_ip_addr }}"
    login: "{{ secret_bmc_username }}"
    password: "{{ secret_bmc_password }}"
    media: cdrom
    image: "{{ provisioner_http_scheme }}://{{ provisioner_server }}:{{ provisioner_http_port }}/{{ cluster.name }}/boot-isos/isos/{{ inventory_hostname }}.iso"
    state: boot_once
  delegate_to: localhost
