- name: Clean up build root directories
  ansible.builtin.file:
    dest: "{{ item }}"
    state: absent
  delegate_to: localhost
  with_items:
    - "{{ iso_tmp_dir }}/ocp-iso-build"
    - "{{ iso_tmp_dir }}/ocp-iso-build/isos"
