- name: Build temp directory
  ansible.builtin.file:
    path: "{{ files_dir }}/fcct_fragment_read"
    state: directory
    mode: "0755"

- name: Copy fragments to read directory
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ files_dir }}/fcct_fragment_read/{{ ansible_loop.index }}.yml"
    mode: "0644"
  loop: "{{ additional_ignition_fragments }}"
  loop_control:
    extended: true

- name: Read FCCT Fragments into Ansible
  ansible.builtin.include_vars:
    dir: "{{ files_dir }}/fcct_fragment_read"
    name: additional_ignition

- name: Debug ignition
  ansible.builtin.debug:
    var: additional_ignition

- name: Remove temp directory
  ansible.builtin.file:
    path: "{{ files_dir }}/fcct_fragment_read"
    state: absent

- name: Render Combined FCCT Config
  ansible.builtin.template:
    src: fcct-wrapper.yaml.j2
    dest: "{{ files_dir }}/combined-fcct.fcc"
    mode: "0644"

- name: Generate Combined Ignition
  ansible.builtin.shell: |
    #!/bin/bash
    podman run -i --rm {{ fcct_image }} --pretty --strict < {{ files_dir }}/combined-fcct.fcc > {{ files_dir }}/combined-ignition.ign
