- name: Render FCCT Fragment
  ansible.builtin.template:
    src: installer-customization.bu.j2
    dest: "{{ files_dir }}/installer-customization-fragment.yaml"
    mode: "0644"

- name: Save fragment path
  ansible.builtin.set_fact:
    inst_customize_fragment_path: "{{ files_dir }}/installer-customization-fragment.yaml"

- name: Register FCCT Fragment
  ansible.builtin.set_fact:
    additional_ignition_fragments: "{{ additional_ignition_fragments + [inst_customize_fragment_path] }}"
