- name: Render FCCT Fragment
  ansible.builtin.template:
    src: tls-ca-fcct-fragment.yaml.j2
    dest: "{{ files_dir }}/tls-ca-fcct-fragment.yaml"
    mode: "0644"

- name: Save fragment path
  ansible.builtin.set_fact:
    tls_fragment_path: "{{ files_dir }}/tls-ca-fcct-fragment.yaml"

- name: Register FCCT Fragment
  ansible.builtin.set_fact:
    additional_ignition_fragments: "{{ additional_ignition_fragments + [tls_fragment_path] }}"
